### ISSUE TITLE
Kopije in stare datoteke

### ISSUE THREAD

**Issue by jaanos** [MarvinHerzog/Trgovina#1]
Na repozitoriju imate nekaj map in datotek, ki imajo v imenu označeno, da gre za kopije ali stare različice. Teh nočete imeti na repozitoriju - kopij tako ali tako ne potrebujete, stare različice pa hrani že sam git. Morda lahko dodaste ustrezno vrstico v `.gitignore`, da preprečite dodajanje neželenih datotek.

**Comment by MarvinHerzog** [comment]
V zadnjih fazah projekta sem seveda nameraval te odstraniti. Trenutno so na gitu zato, da si lahko moja partnerja ogledata kodo, sam pa raje lokalno primerjam stare razlicice z novimi kot preko gita.

**Comment by jaanos** [comment]
Odločitev je seveda vaša, a poanta gita je ravno ta, da se to ne počne (kaj, ko bo več kot ena stara različica?). Če hočeš primerjati lokalno, lahko to seveda počneš, a starih kopij ne potrebuješ na repozitoriju. Kar se pa starih različic tiče, pa lahko v eno datoteko zberete povezave do relevantnih starih različic (če je to seveda smiselno).

To zadevo bom zaenkrat pustil odprto - zaprite jo, ko se vam zdi primerno.

**Comment by MarvinHerzog** [comment]
Odstranil večinoma vse kopije in stare različice.
